import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "100", "200", "300", "500", "600", "800"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var link = document.createElement('link');
                  link.rel = 'stylesheet';
                  var _NEXT_THEME_ID = 'dark-theme-provider'; 
                  link.href = 'https://aamir.zoviotech.com/theme-provider/lillians/style.css';
                  link.id = _NEXT_THEME_ID;
                  document.head.appendChild(link);
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
